import path from 'path';
import type { ComposeInfo } from './container-recreate.js';

/**
 * Everything the UI needs to walk the user through mounting external stack
 * directories into Homer's container: a ready-to-paste compose override file
 * and the command that applies it.
 */
export interface MountGuide {
  /** Host directories that need an identical-path mount (sorted, unique). */
  dirs: string[];
  /** Where to create the override, next to Homer's own compose file. Null when Homer's own stack is unknown (dev mode). */
  overrideFile: string | null;
  /** Full YAML content of the override file. */
  overrideContent: string;
  /** Command applying the override (recreates Homer's container). Null when Homer's own stack is unknown. */
  upCommand: string | null;
  /** Homer's own compose files already include an override — complete it instead of creating it. */
  overrideExists: boolean;
}

/** A directory to mount and the external project(s) that live in it. */
export interface MountEntry {
  dir: string;
  project: string;
}

/** How to recreate Homer's own stack from a detached helper container. */
export interface ApplyPlan {
  cwd: string;
  overrideFile: string;
  /** Host dirs the helper container must mount to read the compose files. */
  mountDirs: string[];
  /** docker argv (after the binary) recreating the stack. */
  composeArgs: string[];
}

// Base names compose auto-loads an override for when run without -f.
const AUTO_LOAD_BASENAMES = new Set(['docker-compose.yml', 'docker-compose.yaml', 'compose.yml', 'compose.yaml']);

function isOverrideFile(file: string): boolean {
  return /override\.ya?ml$/.test(path.basename(file));
}

function resolveOverride(own: ComposeInfo): { overrideFile: string; overrideExists: boolean; cwd: string; autoLoads: boolean; upFiles: string[] } {
  const existingOverride = own.configFiles.find(isOverrideFile);
  const overrideFile = existingOverride ?? path.join(path.dirname(own.configFiles[0]), 'docker-compose.override.yml');
  const cwd = own.workingDir ?? path.dirname(own.configFiles[0]);
  const autoLoads = own.configFiles.length === 1 && AUTO_LOAD_BASENAMES.has(path.basename(own.configFiles[0]));
  const upFiles = existingOverride ? own.configFiles : [...own.configFiles, overrideFile];
  return { overrideFile, overrideExists: Boolean(existingOverride), cwd, autoLoads, upFiles };
}

export function buildMountGuide(entries: MountEntry[], own: ComposeInfo | null): MountGuide {
  // Group project names per directory, one mount per directory.
  const byDir = new Map<string, string[]>();
  for (const { dir, project } of entries) {
    const projects = byDir.get(dir) ?? [];
    if (!projects.includes(project)) projects.push(project);
    byDir.set(dir, projects);
  }
  const uniqueDirs = [...byDir.keys()].sort();
  const service = own?.service || 'homer';

  const header =
    '# Generated by Homer — mounts external compose project directories into\n' +
    "# Homer's container so it can fully manage them (identical host and container paths).\n" +
    '# A single override file is enough: it covers every external project at once.\n';
  const volumeLines = uniqueDirs
    .map(dir => `      # ${byDir.get(dir)!.join(', ')}\n      - ${dir}:${dir}`)
    .join('\n');
  const overrideContent = `${header}services:\n  ${service}:\n    volumes:\n${volumeLines}\n`;

  if (!own || own.configFiles.length === 0) {
    return { dirs: uniqueDirs, overrideFile: null, overrideContent, upCommand: null, overrideExists: false };
  }

  const { overrideFile, overrideExists, cwd, autoLoads, upFiles } = resolveOverride(own);
  const upCommand = autoLoads
    // Compose picks up docker-compose.override.yml on its own.
    ? `cd ${cwd} && docker compose up -d`
    : `cd ${cwd} && docker compose ${upFiles.map(f => `-f ${f}`).join(' ')} up -d`;

  return { dirs: uniqueDirs, overrideFile, overrideContent, upCommand, overrideExists };
}

export function buildApplyPlan(own: ComposeInfo | null): ApplyPlan | null {
  if (!own || own.configFiles.length === 0) return null;
  const { overrideFile, cwd, autoLoads, upFiles } = resolveOverride(own);
  const composeArgs = autoLoads
    ? ['compose', 'up', '-d']
    : ['compose', ...upFiles.flatMap(f => ['-f', f]), 'up', '-d'];
  const mountDirs = [...new Set([cwd, ...upFiles.map(f => path.dirname(f))])];
  return { cwd, overrideFile, mountDirs, composeArgs };
}
