import { describe, it, expect } from 'vitest';
import { buildMountGuide, buildApplyPlan, buildRecreatePlan, buildHelperRunArgs } from './mount-override.js';
import type { ComposeInfo } from './container-recreate.js';

const OWN: ComposeInfo = {
  project: 'homer',
  service: 'homer',
  configFiles: ['/home/user/homer/docker-compose.yml'],
  workingDir: '/home/user/homer',
};

describe('buildMountGuide', () => {
  it('builds override content, file path and up command from own stack info', () => {
    const guide = buildMountGuide([
      { dir: '/srv/appb', project: 'appb' },
      { dir: '/srv/appa', project: 'appa' },
    ], OWN);
    expect(guide.dirs).toEqual(['/srv/appa', '/srv/appb']);
    expect(guide.overrideFile).toBe('/home/user/homer/docker-compose.override.yml');
    expect(guide.overrideContent).toContain('# Generated by Homer');
    expect(guide.overrideContent).toContain('# A single override file is enough');
    expect(guide.overrideContent).toContain(
      'services:\n  homer:\n    volumes:\n      # appa\n      - /srv/appa:/srv/appa\n      # appb\n      - /srv/appb:/srv/appb\n'
    );
    expect(guide.upCommand).toBe('cd /home/user/homer && docker compose up -d');
    expect(guide.overrideExists).toBe(false);
  });

  it('dedups directories and merges project names sharing a dir', () => {
    const guide = buildMountGuide([
      { dir: '/srv/app', project: 'one' },
      { dir: '/srv/app', project: 'two' },
      { dir: '/srv/app', project: 'one' },
    ], OWN);
    expect(guide.dirs).toEqual(['/srv/app']);
    expect(guide.overrideContent).toContain('      # one, two\n      - /srv/app:/srv/app');
  });

  it('reuses an existing override file and its -f flags', () => {
    const own: ComposeInfo = {
      ...OWN,
      configFiles: ['/home/user/homer/docker-compose.yml', '/home/user/homer/docker-compose.override.yml'],
    };
    const guide = buildMountGuide([{ dir: '/srv/app', project: 'app' }], own);
    expect(guide.overrideExists).toBe(true);
    expect(guide.overrideFile).toBe('/home/user/homer/docker-compose.override.yml');
    expect(guide.upCommand).toBe(
      'cd /home/user/homer && docker compose -f /home/user/homer/docker-compose.yml -f /home/user/homer/docker-compose.override.yml up -d'
    );
  });

  it('repeats -f flags for a non auto-loaded compose file name', () => {
    const own: ComposeInfo = { ...OWN, configFiles: ['/home/user/homer/my-stack.yml'] };
    const guide = buildMountGuide([{ dir: '/srv/app', project: 'app' }], own);
    expect(guide.overrideFile).toBe('/home/user/homer/docker-compose.override.yml');
    expect(guide.upCommand).toBe(
      'cd /home/user/homer && docker compose -f /home/user/homer/my-stack.yml -f /home/user/homer/docker-compose.override.yml up -d'
    );
  });

  it('falls back to generic content when own stack is unknown', () => {
    const guide = buildMountGuide([{ dir: '/srv/app', project: 'app' }], null);
    expect(guide.overrideFile).toBeNull();
    expect(guide.upCommand).toBeNull();
    expect(guide.overrideContent).toContain('  homer:\n');
    expect(guide.overrideContent).toContain('- /srv/app:/srv/app');
  });
});

describe('buildApplyPlan', () => {
  it('uses plain compose up for an auto-loaded override', () => {
    const plan = buildApplyPlan(OWN)!;
    expect(plan.cwd).toBe('/home/user/homer');
    expect(plan.overrideFile).toBe('/home/user/homer/docker-compose.override.yml');
    expect(plan.composeArgs).toEqual(['compose', 'up', '-d']);
    expect(plan.mountDirs).toEqual(['/home/user/homer']);
  });

  it('repeats -f flags including the new override otherwise', () => {
    const plan = buildApplyPlan({ ...OWN, configFiles: ['/home/user/homer/my-stack.yml'] })!;
    expect(plan.composeArgs).toEqual([
      'compose',
      '-f', '/home/user/homer/my-stack.yml',
      '-f', '/home/user/homer/docker-compose.override.yml',
      'up', '-d',
    ]);
  });

  it('returns null without own stack info', () => {
    expect(buildApplyPlan(null)).toBeNull();
  });
});

describe('buildRecreatePlan', () => {
  it('does not inject a not-yet-listed override into the -f flags', () => {
    const plan = buildRecreatePlan({ ...OWN, configFiles: ['/home/user/homer/my-stack.yml'] })!;
    expect(plan.composeArgs).toEqual(['compose', '-f', '/home/user/homer/my-stack.yml', 'up', '-d']);
    expect(plan.mountDirs).toEqual(['/home/user/homer']);
  });

  it('relies on auto-load for standard file names', () => {
    expect(buildRecreatePlan(OWN)!.composeArgs).toEqual(['compose', 'up', '-d']);
  });

  it('returns null without own stack info', () => {
    expect(buildRecreatePlan(null)).toBeNull();
  });
});

describe('buildHelperRunArgs', () => {
  it('builds a detached self-removing helper with socket, mounts, cwd and extra args', () => {
    const plan = buildRecreatePlan(OWN)!;
    expect(buildHelperRunArgs(plan, 'homer:1.2', ['--force-recreate'])).toEqual([
      'run', '-d', '--rm',
      '-v', '/var/run/docker.sock:/var/run/docker.sock',
      '-v', '/home/user/homer:/home/user/homer',
      '-w', '/home/user/homer',
      '--entrypoint', 'docker',
      'homer:1.2',
      'compose', 'up', '-d', '--force-recreate',
    ]);
  });
});
